### ISSUE TITLE
Список интересных тем для докладов по Angular

### ISSUE THREAD

**Issue by obenjiro** [AngularMoscow/Talks#1]
### Темы уже рассказанные на предыдущих докладах:
(не факт что тема была освещена полностью поэтому если есть что добавить или сказать не стесняйтесь предлагать)

- [x] Angular Router  (https://youtu.be/ovsBd6Y5DN0) [version 4.x]
- [x] Динамическое создание компонентов в Angular  (https://youtu.be/blSENg8Gssw) [version 2.x]
- [x] Angular Upgrade (https://youtu.be/fUxAR2LNo-w) [version 2.x]
- [x] Server side rendering (https://youtu.be/YGDJOfwgu-A) [version 2.x]
- [x] Состояние состояния (Services, Redux, Mobx, DCI) - #2

### Темы интересные для следующих докладов

- [ ] NativeScript
- [ ] Ionic Angular
- [ ] NgUpgrade
- [ ] Akita, ngsx
- [ ] Unit test, E2E tests
- [ ] Angular CLI Schematics
- [ ] Angular ivy

### Как внести свой вклад?

Предлагайте тему доклада с кратким описанием через создание нового Issue. Голосуйте за другие темы лайками. Покажите это issue своим коллегам. Нам интересно ваше мнение.

Темы, которые не были уже раскрыты и набирающие достаточно количество голосов, будут добавлены в список. Этот список поможет людям понять докладчикам, что Angular community хочет услышать. Также это поможет вам понять, интересно ли людям будет услышать ваш доклад

PS: Если это ваш доклад - добавляйте в заголовок Issue префикс "Доклад:", если это предложение "Тема:"

**Comment by aiboy** [comment]
### Состояние состояния (Services, Redux, Mobx, DCI) 

Рассмотрим различные способы управления состоянием приложения. Поделим аудиторию на два лагеря. Рассмотрим плюсы и минусы разных подходов:

1) Services - Стандартный подход работы с сервисами.
2) Redux - Stateless Uniderectional Dataflow.
3) Mobx - Главная альтернатива Redux.
4) DCI  - Data Context Interaction - ООП приходит на помощь.
