### ISSUE TITLE
Доклад: Воркеры в жизни и в Angular

### ISSUE THREAD

**Issue by shanhaichik** [AngularMoscow/Talks#10]
Добрый день! 
Есть предложение осветить тему: **Воркеры в Angular**

 В докладе хотелось бы рассмотреть следующие вещи:
1) Кто такие Web Workers, Shared Workers и Service Workers. Какие задачи решают в жизни.
2) Модули **angular/service-worker** и **angular/platform-webworker-dynamic** в экосистеме Angular. Какие задачи, модули, решают из коробки. Конфигурация Service Workers  в Angular CLI. 
3) Демо с использование выше указанных модулей.

**Comment by aiboy** [comment]
@shanhaichik напишите пожалуйста в telegram @Ai_boy
