### ISSUE TITLE
Доклад: Наследование компонентов в Angular

### ISSUE THREAD

**Issue by klimentru1986** [AngularMoscow/Talks#12]
Рассмотрим:
- наследование как парадигма ООП
- наследование в JS/TS
- наследование в Angular 2+
- наследование в Angular 2+ от абстрактного класса
- ситуации в которых можно использовать наследование, плюсы и минусы данного подхода

**Comment by aiboy** [comment]
@klimentru1986 напишите свой e-mail, или отпишитесь мне в Telegram

**Comment by andreyjkee** [comment]
На сколько я знаю, когда послений раз щупал это, были проблемы с тем, что @Inputs, @Outputs не наследуются? Она как-то была решена или есть некий workaround? Хотелось бы об этом тоже услышать.
