### ISSUE TITLE
6 App One Code With Ionic

### ISSUE THREAD

**Issue by saniyusuf** [AngularMoscow/Talks#14]
You and your team have this great Idea and you have your users using different devices and operating systems to access the same application. Some users are on the Web, some on Mobile some of their Desktop and you also have to worry about what operating system they are on and also have to consider how your application is presented on each device & operating system. 

What if there was a way to code your app without worrying too much about operating systems/devices/screen sizes and just focusing on getting your idea across to your users regardless. Join me on a journey where I show you how to use Angular, Ionic & the PWA standard to build apps for IOS, Android, Windows, Web, Mac & PC with the same code all using just HTML5.

Speaker - Sani Yusuf

**Comment by splincode** [comment]
The best
https://www.youtube.com/watch?v=Vf-eZDw08c8
