### ISSUE TITLE
Доклад: Angular Schematics

### ISSUE THREAD

**Issue by FrankiePo** [AngularMoscow/Talks#15]
Рассмотрим:

- с чем едят Angular Devkit и зачем
- разницу между `@schematics/angular` и `@angular-devkit/schematics`
- создание и использование собственных коллекций
- генерацию и тестирование коллекций
- небольшое демо со ссылкой на проект

**Comment by aiboy** [comment]
@FrankiePo напишите слой e-mail или telegram login
