### ISSUE TITLE
Доклад: Что такое TemplateRef, ViewContainerRef и как упростить разработку с помощью <ng-template>.

### ISSUE THREAD

**Issue by demenskiy** [AngularMoscow/Talks#16]
1. Что такое [`TemplateRef`](https://angular.io/api/core/TemplateRef)?
2. Что такое [`ViewContainerRef`](https://angular.io/api/core/ViewContainerRef)?
3. Какое это всё имеет отношение к `<ng-template>` и `<ng-container>`?
4. Как умение работать с `<ng-template>` поможет упростить разработку?

**Comment by aiboy** [comment]
Напиши в Telegram @Ai_boy
