### ISSUE TITLE
Доклад: Практическое применение ngrx 4.x

### ISSUE THREAD

**Issue by skhrolenok** [AngularMoscow/Talks#18]
1. Состояние приложения (Application state).
2. Библиотеки ngrx (store, router, effects, devtools).
3. Шаблоны, приемы и прочие методы применения и тестирования (marble testing) ngrx на практике.

**Comment by splincode** [comment]
Хотелось бы еще, чтобы вы не просто осветили ngrx, а в контексте сравнений с другими подходами Redux vs Singleton Service vs ..., чтобы понимать почему следует в каких-то задачах или случаях использовать именно такой подход.

Был доклад "Состояние состояния":
https://www.youtube.com/watch?v=8VesYob7OJg

Но там было просто рассказано, что вы можете использовать такие-то вещи в Angular, но не сказано, что лучше приживается в Angular и что в перспективе лучше использовать.

**Comment by aiboy** [comment]
@splincode Нет не надо. На доклад в среднем 20 минут никакого глубокого сравнения нельзя сделать за это время. @skhrolenok Доклад будет мега интересный - возьмем его сразу как сможем

**Comment by splincode** [comment]
Вас понял, вопросов нет.
