### ISSUE TITLE
Доклад: Стратегия обнаружения изменений в Angular

### ISSUE THREAD

**Issue by splincode** [AngularMoscow/Talks#20]
1. **Хороший, плохой, злой DOM**
- Что такое критический путь рендеринга
- Является ли DOM медленным?
- Рендеринг HTML/CSS через WebGL
2. **Что такое MVVW (Model, View, ViewModel)?**
- Компонентная архитектура
3.  **Основное различие между двусторонним связыванием данных и однонаправленным потоком**
- Почему ReactJS использует one-way data-binding?
- Polymer Shadow DOM vs ReactJS Virtual DOM
- Почему при разработке Angular 2 отказались от Virtual DOM?
- Почему VueJS использует two-way data-binding и Virtual DOM
4. **Стратегии оптимизации в Angular**
- Примеры связывания моделей данных в шаблонах
- Уменьшение количества проверок (ChangeDetection)
- Экономия ресурсов процессора с использование trackByFunction
- Ненужные вычисления значений в шаблоне
- Отключение обнаружения
5. **Умные стратегии обнаружения**
- Что такое ngZone
- Immutable Objects
- Observables streams

**Comment by splincode** [comment]
Когда людям интересно совсем другое:
![image](https://user-images.githubusercontent.com/12021443/33395599-1d961030-d557-11e7-9d25-61fb07e2d59d.png)

**Comment by aiboy** [comment]
Закрываю пока из за того что уже было на AngularPiter.
