### ISSUE TITLE
Тема: "Профилировка и оптимизация приложения на Angular"

### ISSUE THREAD

**Issue by EvAlex** [AngularMoscow/Talks#3]
Предлагаю тему для доклада: "Профилировка и оптимизация приложения на Angular". Тема слабо или никак не освещена в документации, и я не слышал подобных докладов на ng-conf (пропустил?).

Вопросы, которые хотелось бы обсудить:

- Профилировка приложения. Chrome Dev Tools или что-то другое? Как, на что обращать внимание, как бороться с узкими, но глубокими "колодцами" в результатах профилировки?
- Как проектировать структуры данных в приложении и компоненты, чтобы предупредить возникновение узких мест в производительности приложения?
- Как правильно готовить приложения, получающие данные по Web Sockets? Данные, прилетающие слишком часто "вешают" страницу. Что делать? Прореживать обработчики или что-то ещё?
- Как уменьшить количество вызовов DOM Sanitizer-a при отрисовке компонентов? При использовании data-binding-ов в стилях, особенно с процентами и calc-ами наблюдается серьёзная просадка. Как быть, если надо рисовать простую, но специфичную графику, где параметры вычисляются в js? Переходить на svg или всё же оптимизировать css и data-binding-и? Использовать data-binding для svg или рисовать "руками"?

Если Issue соберёт много голосов, я готов рассмотреть возможность стать докладчиком на эту тему.

**Comment by aiboy** [comment]
@EvAlex Это предложение доклада от вас или просто предлагаете тему которую интересно было бы услышать?

**Comment by EvAlex** [comment]
@aiboy Было бы интересно услышать, но если будет много голосов и не найдётся докладчика, то я рассмотрю идею сделать доклад самому.
