### ISSUE TITLE
Доклад: Динамика в Angular. Формы, таблицы, виджеты

### ISSUE THREAD

**Issue by thekiba** [AngularMoscow/Talks#33]
В прошлом докладе мы рассматривали биндинг динамических компонентов.
В этот раз мы постараемся ответить на некоторые популярные вопросы, как:
- Нужна ли в моем приложении динамика?
- Как создать динамическую форму?
- Будут ли сложности в поддержке и развитии в дальнейшем?

Также, мы попробуем ответить на один из главных вопросов, а именно
Так ли просто реализовать динамический UI, как это может показаться на первый взгляд?

**Comment by splincode** [comment]
@aiboy need to close
