### ISSUE TITLE
Доклад: NGRX vs NGXS

### ISSUE THREAD

**Issue by kyusupov33** [AngularMoscow/Talks#34]
**Введение:**
- Зачем нам нужен state management 
________________
**Основная часть:**
1. redux
- Концепция
- Иллюстрация в маленьких и больших проектах
2. ngxs
- Концепция
- Иллюстрация в маленьких и больших проектах
3. vuex
- Концепция
- Иллюстрация в маленьких и больших проектах
________________
**Заключение:**
- Актуальность mobx для angular, vue
- Почему следует использовать ngxs, а не ngrx
- Почему выбор фреймворка не так важен, чем выбор store?
________________
**Выступающие:**
@kyusupov33,
@splincode

**Comment by splincode** [comment]
@kyusupov33 переименуй тему на NGRX vs NGXS

**Comment by kyusupov33** [comment]
@splincode переименовал

**Comment by obenjiro** [comment]
закрываю because of issuer
