### ISSUE TITLE
Unit тестирование с Jest и ts-mockito

### ISSUE THREAD

**Issue by klimentru1986** [AngularMoscow/Talks#45]
Кратко по докладу:
1. что такое unit тестирование;
2. зачем писать тесты;
3. библиотеки для тестирования;
4. структура теста;
5. подмена окружения с ts-mockito;
6. тестирование сервисов, пайпов, директив и компонентов.

**Comment by shoom3301** [comment]
Стоит подробнее раскрыть тему "Зачем вообще мокировать?".
В каких случаях это нужно, в каких нет.
