### ISSUE TITLE
Доклад: Ангуляры в Ангуляре, или как мы сделали мультиапп в Тинькофф.Бизнес.

### ISSUE THREAD

**Issue by annnger** [AngularMoscow/Talks#47]
1 Что такое микрофронтенд и какие проблемы он решает.
2 Типичные подходы реализации (web components, библиотеки (h-include, single-spa), lazy-loading)
3 Реализация с помощью iframe
4 Сопутствующие проблемы в iframe реализации (роутинг, отслеживание высоты iframe, общение между приложениями через postMessage и др.)
5 Что из себя представляют приложения Тинькофф.Бизнес
6 Концепция разделения приложений Тинькофф.Бизнес и объединения их под общим UI
7 Как мы решали возникшие проблемы с микрофронтендом в Тинькофф.Бизнес (поддержка предыдущих версий,  единая авторизация, разные стили и др.)
8 Описание работы готового продукта

**Comment by vorant94** [comment]
привет всем, а есть где-то сам доклад посмотреть? у нас в фирме сейчас поднялся вопрос перехода на микрофронтенды и чем больше ресурсов есть по теме, тем лучше...
