### ISSUE TITLE
Доклад: Препарируем RxJS операторы

### ISSUE THREAD

**Issue by qeireal** [AngularMoscow/Talks#50]
1. Рассмотрим исходники 🧐
1.1. различных Subscribable сущностей; 👀
1.2. операторов RxJS; 🔧
2. Разберем ситуации, в которых дефолтных операторов может не хватать; 🤯
3. Напишем несколько своих кастомных операторов (демки). 👨‍💻

**Comment by skhrolenok** [comment]
жду transducer на rxjs
