### ISSUE TITLE
Доклад: EventManager в Angular

### ISSUE THREAD

**Issue by waterplea** [AngularMoscow/Talks#63]
Как вы думаете, что происходит в Angular, когда вы пишете в шалоне `(click)`  или `@HostListener('click')` в коде директивы? У Angular есть сервис под названием `EventManager`, который можно расширять с помощью плагинов. Именно благодаря им вы пишете `(keydown.enter)` и не реагируете на нажатие остальных клавиш. Кроме внутренних плагинов мы можем добавлять свои, давайте добавим плагин, который будет останавливать всплытие события и рассмотрим, какие ещё более сложные штуки доступны для нас благодаря этому API.

**Comment by YuliaTsareva** [comment]
Доклад прочитан на AngularMoscow 17 👍
https://meetup.tinkoff.ru/event/angular-meetup-17/
