### ISSUE TITLE
Доклад: RxJS Subjects.

### ISSUE THREAD

**Issue by aalexeev239** [AngularMoscow/Talks#7]
Разберем, что такое сабджекты. Какие бывают, чем отличаются друг от друга. Когда и какие используются. Рассмотрим multicasting-операторы. Приведу примеры использования сабджектов.
Доклад требует поверхностного знакомства с rxjs и Observable.

**Comment by aiboy** [comment]
@aalexeev239 напишите свой e-mail, или отпишитесь мне в Telegram
