### ISSUE TITLE
Доклад: Angular Universal 4.x

### ISSUE THREAD

**Issue by Gorniv** [AngularMoscow/Talks#8]
Примерный список вопросов из презентации:
1. Как создать приложение Universal
2. Angular-cli и  universal
3. RenderFactory и server.ts
4. Почему рендерится какая-то фигня
5. Как убрать двойной вызов backend
6. Как сделать авторизацию?
7. Разделение реализаций(клиент-сервер)
8. Тонкая насройка в компоненте
9. UI компоненты и SSR
          - primeng
          - ngx-bootstrap
          - material
10. Window, document, localstorage

**Comment by u3c** [comment]
На самом деле, серьёзной актуальности тема.
